### PR TITLE
Added an src directory and linked in the places code live in the docroot

### PR DESCRIPTION
**Pull request by johnennewdeeson**
Suggestion for an src directory in the docroot on Drupal projects.

Put the frontend folder in there if there is one.

Added symlinks to:
* sites/all/conf
* sites/all/modules/custom
* sites/all/themes/custom

Just gathers things together nearer the project root and so a bit easier to find.

Just a suggestion...

### CODE REVIEW

**Review by mikeddeeson — COMMENTED** [review]
Why do you need the symlinks in the src directory pointing to drupal directories?

**Comment by angry-dan** [comment]
I see why you'd want this. One of the most annoying things about PHPStorm is that it follows symlinks, even if they are inside your project. This means that when it's indexing your code it indexes symlinked paths twice. This gets compounded when you have a symlink that includes a node_modules folder or anything big like that.

I still think we should do this, but maybe we should also include the relevant "ignore these places" config for PHPStorm to stop it double indexing everything in your project.

**Comment by mikeddeeson** [comment]
You can mark directories as 'excluded' in PHPStorm so that it won't index
them, but if we could do this with a config file for the project that would
be great.

**Comment by ghost** [comment]
Yeah, I get the PHP Storm thing and I mark as excluded like Mike does.

**Review by adam-dg — COMMENTED** [review]
I like the idea of this change a lot.
It brings the D7 Quickstart inline with the D8 Quickstart and greater consistency can only be a good thing.

While the change is small it introduces enough entropy to warrant some testing under local dev and under Pipelines to ensure there are no regressions.

I'll aim to do this testing and reported back within a couple of weeks.

**Comment by ghost** [comment]
I'm doing this on my projects already and no one has died. Again, this is just recommendations - specific projects will likely have different places to have to symlink too so would need though before including on any specific project.

**Pull request merged**
