### PR TITLE
Make build scripts fail pipelines

### PR DESCRIPTION
**Pull request by johnennewdeeson**
Added bash error so that scripts cause the thing that runs them to fail, like pipelines

### CODE REVIEW

**Review by mikeddeeson — APPROVED** [review]

**Comment by angry-dan** [comment]
I like this, whilst you're at it maybe also `set -x` too so that when you review the pipelines log you can see which line caused the script to fail.

**Comment by ghost** [comment]
Bit noisy but it works

**Review by adam-dg — CHANGES_REQUESTED** [review]
Adding the -e flag on the build scripts is something that is long overdue.

It seems to me that the -x flag add too much noise to Pipelines and under local dev for this to be a default option.

I'd rather leave out the explicit setting of -x in the scripts.
Instead I think we should add a settings to the .build.env file which allows you to set on a per project/branch basis whether you want the -x option to be set by Bash.

In .build.env we could introduce a variable of "debug" or maybe "build_debug" which can be set to "Y" or "N"
In the scripts if debug / build_debug is set to "Y" then we set the -x option and in all other cases we leave well only.

This approach maintains the current (and expected) function of the build scripts while introducing a provision for debugging or greater verbosity for those who wish to take advantage of it.

**Comment by ghost** [comment]
I like the idea of debug mode. I should probably have move -x into its own branch so we couild get -e in as its important

**Pull request merged**
